In [ ]:
!pip install --upgrade pip

Requirement already satisfied: pip in /opt/conda/lib/python3.10/site-packages (24.0)

In [ ]:
from kerykeion import AstrologicalSubject
kanye = AstrologicalSubject("Kanye", 1977, 6, 8, 8, 45, "Atlanta")
kanye.sun

{'name': 'Sun', 'quality': 'Mutable', 'element': 'Air', 'sign': 'Gem', 'sign_num': 2, 'position': 17.598992059774275, 'abs_pos': 77.59899205977428, 'emoji': '♊️', 'point_type': 'Planet', 'house': 'Twelfth_House', 'retrograde': False}

In [ ]:
kanye.first_house

{'name': 'First_House', 'quality': 'Cardinal', 'element': 'Water', 'sign': 'Can', 'sign_num': 3, 'position': 17.995779673209114, 'abs_pos': 107.99577967320911, 'emoji': '♋️', 'point_type': 'House'}

In [ ]:
kanye.moon.element

'Water'

In [ ]:
import matplotlib.pyplot as plt
from kerykeion import AstrologicalSubject, KerykeionChartSVG

In [ ]:
from kerykeion import AstrologicalSubject, KerykeionChartSVG

first = AstrologicalSubject("Jack", 1990, 6, 15, 15, 15, "Roma")
second = AstrologicalSubject("Jane", 1991, 10, 25, 21, 00, "Roma")

# Set the type, it can be Natal, Synastry or Transit

name = KerykeionChartSVG(first, chart_type="Synastry", second_obj=second)
name.makeSVG()
print(len(name.aspects_list))

69

In [ ]:
from kerykeion import Report, AstrologicalSubject

kanye = AstrologicalSubject("Kanye", 1977, 6, 8, 8, 45, "Atlanta")
report = Report(kanye)
report.print_report()

+- Kerykeion report for Kanye -+
+----------+------+-------------+-----------+----------+
| Date     | Time | Location    | Longitude | Latitude |
+----------+------+-------------+-----------+----------+
| 8/6/1977 | 8:45 | Atlanta, US | -84.38798 | 33.749   |
+----------+------+-------------+-----------+----------+
+-----------+------+-------+------+----------------+
| Planet    | Sign | Pos.  | Ret. | House          |
+-----------+------+-------+------+----------------+
| Sun       | Gem  | 17.6  | -    | Twelfth_House  |
| Moon      | Pis  | 16.43 | -    | Ninth_House    |
| Mercury   | Tau  | 26.29 | -    | Eleventh_House |
| Venus     | Tau  | 2.03  | -    | Tenth_House    |
| Mars      | Tau  | 1.79  | -    | Tenth_House    |
| Jupiter   | Gem  | 14.61 | -    | Eleventh_House |
| Saturn    | Leo  | 12.8  | -    | Second_House   |
| Uranus    | Sco  | 8.27  | R    | Fourth_House   |
| Neptune   | Sag  | 14.69 | R    | Fifth_House    |
| Pluto     | Lib  | 11.45 | R    | Fourth_House   |
| Mean_Node | Lib  | 21.49 | R    | Fourth_House   |
| True_Node | Lib  | 22.82 | R    | Fourth_House   |
| Chiron    | Tau  | 4.17  | -    | Tenth_House    |
+-----------+------+-------+------+----------------+
+----------------+------+----------+
| House          | Sign | Position |
+----------------+------+----------+
| First_House    | Can  | 18.0     |
| Second_House   | Leo  | 9.51     |
| Third_House    | Vir  | 4.02     |
| Fourth_House   | Lib  | 3.98     |
| Fifth_House    | Sco  | 9.39     |
| Sixth_House    | Sag  | 15.68    |
| Seventh_House  | Cap  | 18.0     |
| Eighth_House   | Aqu  | 9.51     |
| Ninth_House    | Pis  | 4.02     |
| Tenth_House    | Ari  | 3.98     |
| Eleventh_House | Tau  | 9.39     |
| Twelfth_House  | Gem  | 15.68    |
+----------------+------+----------+

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/kaggle/input/kaushald/QSVLe4NFtgRd4CGwtV82M51KP8H3_file-1Kfo84HWUpxrRk1Ou0ebU6bt_sandbox__mnt_data_famous_people_birthdays.txt")

In [ ]:
df

,Name,Year,Month,Day,Hour,Minutes,City,Nation
0,Barack Obama,1961,8,4,19,24,Honolulu,United States
1,Oprah Winfrey,1954,1,29,4,30,Kosciusko,United States
2,Nelson Mandela,1918,7,18,14,54,Mvezo,South Africa
3,Queen Elizabeth II,1926,4,21,2,40,London,United Kingdom
4,Dalai Lama,1935,7,6,4,38,Taktser,China
5,Angelina Jolie,1975,6,4,9,9,Los Angeles,United States
6,Mahatma Gandhi,1869,10,2,7,30,Porbandar,India
7,Albert Einstein,1879,3,14,11,30,Ulm,Germany
8,Malala Yousafzai,1997,7,12,8,10,Mingora,Pakistan
9,Lionel Messi,1987,6,24,20,20,Rosario,Argentina
10,Elon Musk,1971,6,28,12,0,Pretoria,South Africa
11,Serena Williams,1981,9,26,18,53,Saginaw,United States
12,Cristiano Ronaldo,1985,2,5,10,20,Funchal,Portugal
13,Muhammad Ali,1942,1,17,18,35,Louisville,United States
14,Tom Hanks,1956,7,9,11,17,Concord,United States
15,Mother Teresa,1910,8,26,14,25,Skopje,North Macedonia
16,Stephen Hawking,1942,1,8,4,0,Oxford,United Kingdom
17,Michael Jordan,1963,2,17,13,40,New York City,United States
18,Leonardo da Vinci,1452,4,15,21,40,Anchiano,Italy
19,Steve Jobs,1955,2,24,19,15,San Francisco,United States
20,Pablo Picasso,1881,10,25,23,15,Málaga,Spain
21,Meryl Streep,1949,6,22,8,5,Summit,United States
22,Bill Gates,1955,10,28,22,0,Seattle,United States
23,Amitabh Bachchan,1942,10,11,16,5,Allahabad,India
24,Vincent van Gogh,1853,3,30,11,0,Zundert,Netherlands
25,Sigmund Freud,1856,5,6,18,30,Freiberg,Czech Republic
26,Roger Federer,1981,8,8,8,40,Basel,Switzerland
27,Usain Bolt,1986,8,21,13,0,Sherwood Content,Jamaica
28,Frida Kahlo,1907,7,6,8,30,Coyoacán,Mexico
29,Walt Disney,1901,12,5,0,35,Chicago,United States
30,Audrey Hepburn,1929,5,4,3,0,Ixelles,Belgium
31,Marie Curie,1867,11,7,19,0,Warsaw,Poland
32,John Lennon,1940,10,9,18,30,Liverpool,United Kingdom
33,Pele,1940,10,23,3,0,Três Corações,Brazil
34,Marilyn Monroe,1926,6,1,9,30,Los Angeles,United States
35,Abraham Lincoln,1809,2,12,6,54,Hodgenville,United States
36,Charles Darwin,1809,2,12,8,30,Shrewsbury,United Kingdom
37,Galileo Galilei,1564,2,15,18,30,Pisa,Italy
38,William Shakespeare,1564,4,23,0,0,Stratford-upon-Avon,United Kingdom
39,Ludwig van Beethoven,1770,12,17,2,0,Bonn,Germany
40,Aung San Suu Kyi,1945,6,19,13,15,Rangoon,Myanmar
41,Isaac Newton,1643,1,4,1,38,Woolsthorpe-by-Colsterworth,United Kingdom
42,Nikola Tesla,1856,7,10,2,24,Smiljan,Croatia
43,Rosa Parks,1913,2,4,19,0,Tuskegee,United States
44,Martin Luther King Jr.,1929,1,15,12,0,Atlanta,United States
45,Thomas Edison,1847,2,11,3,0,Milan,United States
46,J.K. Rowling,1965,7,31,0,45,Yate,United Kingdom
47,Fyodor Dostoevsky,1821,11,11,16,38,Moscow,Russia
48,Leo Tolstoy,1828,9,9,3,5,Yasnaya Polyana,Russia
49,Anne Frank,1929,6,12,7,30,Frankfurt,Germany
50,Elvis Presley,1935,1,8,4,35,Tupelo,United States
51,Michael Jackson,1958,8,29,19,33,Gary,United States
52,Immanuel Kant,1724,4,22,5,0,Königsberg,Prussia
53,Friedrich Nietzsche,1844,10,15,10,0,Röcken,Germany
54,Virginia Woolf,1882,1,25,12,0,London,United Kingdom
55,Rabindranath Tagore,1861,5,7,12,10,Kolkata,India
56,Alfred Hitchcock,1899,8,13,3,30,London,United Kingdom
57,Coco Chanel,1883,8,19,4,0,Saumur,France
58,Plato,428,1,1,0,0,Athens,Greece
59,Aristotle,384,1,1,0,0,Stagira,Greece

In [ ]:
import swisseph as swe

In [ ]:
swe.set_ephe_path('/opt/conda/lib/python3.10/site-packages/kerykeion/sweph/')

In [ ]:
import pandas as pd
from kerykeion import AstrologicalSubject

astrological_subjects = []
for _, row in df.head(4).iterrows():
    a = AstrologicalSubject(str(row["Name"]), row["Year"], row["Month"], row["Day"], row["Hour"], row["Minutes"], str(row["City"],))
    astrological_subjects.append(a)

In [ ]:
for i in astrological_subjects:
    print(i.sun)

{'name': 'Sun', 'quality': 'Fixed', 'element': 'Fire', 'sign': 'Leo', 'sign_num': 4, 'position': 12.547554241241812, 'abs_pos': 132.5475542412418, 'emoji': '♌️', 'point_type': 'Planet', 'house': 'Sixth_House', 'retrograde': False}
{'name': 'Sun', 'quality': 'Fixed', 'element': 'Air', 'sign': 'Aqu', 'sign_num': 10, 'position': 8.992825351007468, 'abs_pos': 308.99282535100747, 'emoji': '♒️', 'point_type': 'Planet', 'house': 'Second_House', 'retrograde': False}
{'name': 'Sun', 'quality': 'Cardinal', 'element': 'Water', 'sign': 'Can', 'sign_num': 3, 'position': 25.070565725218998, 'abs_pos': 115.070565725219, 'emoji': '♋️', 'point_type': 'Planet', 'house': 'Eighth_House', 'retrograde': False}
{'name': 'Sun', 'quality': 'Fixed', 'element': 'Earth', 'sign': 'Tau', 'sign_num': 1, 'position': 0.20567719925425365, 'abs_pos': 30.205677199254254, 'emoji': '♉️', 'point_type': 'Planet', 'house': 'Second_House', 'retrograde': False}

In [ ]:
from kerykeion import AstrologicalSubject, KerykeionChartSVG

first = AstrologicalSubject("Jack", 1990, 6, 15, 15, 15, "Roma")
second = AstrologicalSubject("Jane", 1991, 10, 25, 21, 00, "Roma")

# Set the type, it can be Natal, Synastry or Transit

name = KerykeionChartSVG(first, chart_type="Synastry", second_obj=second)
try:
    name.makeSVG()
except Exception as e:
    print("Error occurred while generating SVG:", str(e))

In [ ]:
for i in astrological_subjects:
    report = Report(i)
    report.print_report()

+- Kerykeion report for Barack Obama -+
+----------+-------+--------------+------------+----------+
| Date     | Time  | Location     | Longitude  | Latitude |
+----------+-------+--------------+------------+----------+
| 4/8/1961 | 19:24 | Honolulu, US | -157.85833 | 21.30694 |
+----------+-------+--------------+------------+----------+
+-----------+------+-------+------+---------------+
| Planet    | Sign | Pos.  | Ret. | House         |
+-----------+------+-------+------+---------------+
| Sun       | Leo  | 12.55 | -    | Sixth_House   |
| Moon      | Gem  | 3.35  | -    | Fourth_House  |
| Mercury   | Leo  | 2.33  | -    | Sixth_House   |
| Venus     | Can  | 1.79  | -    | Fifth_House   |
| Mars      | Vir  | 22.58 | -    | Seventh_House |
| Jupiter   | Aqu  | 0.86  | R    | Twelfth_House |
| Saturn    | Cap  | 25.33 | R    | Twelfth_House |
| Uranus    | Leo  | 25.27 | -    | Seventh_House |
| Neptune   | Sco  | 8.61  | -    | Ninth_House   |
| Pluto     | Vir  | 6.98  | -    | Seventh_House |
| Mean_Node | Leo  | 27.89 | R    | Seventh_House |
| True_Node | Leo  | 27.3  | R    | Seventh_House |
| Chiron    | Pis  | 5.32  | R    | First_House   |
+-----------+------+-------+------+---------------+
+----------------+------+----------+
| House          | Sign | Position |
+----------------+------+----------+
| First_House    | Aqu  | 18.05    |
| Second_House   | Pis  | 25.91    |
| Third_House    | Tau  | 0.3      |
| Fourth_House   | Tau  | 28.89    |
| Fifth_House    | Gem  | 23.98    |
| Sixth_House    | Can  | 19.02    |
| Seventh_House  | Leo  | 18.05    |
| Eighth_House   | Vir  | 25.91    |
| Ninth_House    | Sco  | 0.3      |
| Tenth_House    | Sco  | 28.89    |
| Eleventh_House | Sag  | 23.98    |
| Twelfth_House  | Cap  | 19.02    |
+----------------+------+----------+

+- Kerykeion report for Oprah Winfrey -+
+-----------+------+---------------+-----------+----------+
| Date      | Time | Location      | Longitude | Latitude |
+-----------+------+---------------+-----------+----------+
| 29/1/1954 | 4:30 | Kosciusko, US | -85.86072 | 41.2441  |
+-----------+------+---------------+-----------+----------+
+-----------+------+-------+------+----------------+
| Planet    | Sign | Pos.  | Ret. | House          |
+-----------+------+-------+------+----------------+
| Sun       | Aqu  | 8.99  | -    | Second_House   |
| Moon      | Sag  | 4.53  | -    | Eleventh_House |
| Mercury   | Aqu  | 19.16 | -    | Second_House   |
| Venus     | Aqu  | 8.85  | -    | Second_House   |
| Mars      | Sco  | 23.58 | -    | Eleventh_House |
| Jupiter   | Gem  | 16.66 | R    | Sixth_House    |
| Saturn    | Sco  | 9.04  | -    | Tenth_House    |
| Uranus    | Can  | 20.31 | R    | Seventh_House  |
| Neptune   | Lib  | 26.06 | R    | Tenth_House    |
| Pluto     | Leo  | 24.15 | R    | Eighth_House   |
| Mean_Node | Cap  | 23.25 | R    | First_House    |
| True_Node | Cap  | 23.93 | -    | First_House    |
| Chiron    | Cap  | 23.59 | -    | First_House    |
+-----------+------+-------+------+----------------+
+----------------+------+----------+
| House          | Sign | Position |
+----------------+------+----------+
| First_House    | Sag  | 27.66    |
| Second_House   | Aqu  | 5.81     |
| Third_House    | Pis  | 17.29    |
| Fourth_House   | Ari  | 21.4     |
| Fifth_House    | Tau  | 17.08    |
| Sixth_House    | Gem  | 7.97     |
| Seventh_House  | Gem  | 27.66    |
| Eighth_House   | Leo  | 5.81     |
| Ninth_House    | Vir  | 17.29    |
| Tenth_House    | Lib  | 21.4     |
| Eleventh_House | Sco  | 17.08    |
| Twelfth_House  | Sag  | 7.97     |
+----------------+------+----------+

+- Kerykeion report for Nelson Mandela -+
+-----------+-------+-----------+-----------+-----------+
| Date      | Time  | Location  | Longitude | Latitude  |
+-----------+-------+-----------+-----------+-----------+
| 18/7/1918 | 14:54 | Mvezo, ZA | 28.51793  | -31.94948 |
+-----------+-------+-----------+-----------+-----------+
+-----------+------+-------+------+----------------+
| Planet    | Sign | Pos.  | Ret. | House          |
+-----------+------+-------+------+----------------+
| Sun       | Can  | 25.07 | -    | Eighth_House   |
| Moon      | Sco  | 20.25 | -    | Twelfth_House  |
| Mercury   | Leo  | 16.13 | -    | Ninth_House    |
| Venus     | Gem  | 22.58 | -    | Sixth_House    |
| Mars      | Lib  | 12.58 | -    | Eleventh_House |
| Jupiter   | Can  | 1.17  | -    | Seventh_House  |
| Saturn    | Leo  | 15.03 | -    | Ninth_House    |
| Uranus    | Aqu  | 26.93 | R    | Third_House    |
| Neptune   | Leo  | 6.38  | -    | Eighth_House   |
| Pluto     | Can  | 5.54  | -    | Seventh_House  |
| Mean_Node | Sag  | 20.53 | R    | Twelfth_House  |
| True_Node | Sag  | 21.83 | -    | Twelfth_House  |
| Chiron    | Ari  | 3.42  | R    | Fourth_House   |
+-----------+------+-------+------+----------------+
+----------------+------+----------+
| House          | Sign | Position |
+----------------+------+----------+
| First_House    | Sag  | 23.68    |
| Second_House   | Cap  | 16.14    |
| Third_House    | Aqu  | 9.01     |
| Fourth_House   | Pis  | 5.74     |
| Fifth_House    | Ari  | 9.02     |
| Sixth_House    | Tau  | 17.34    |
| Seventh_House  | Gem  | 23.68    |
| Eighth_House   | Can  | 16.14    |
| Ninth_House    | Leo  | 9.01     |
| Tenth_House    | Vir  | 5.74     |
| Eleventh_House | Lib  | 9.02     |
| Twelfth_House  | Sco  | 17.34    |
+----------------+------+----------+

+- Kerykeion report for Queen Elizabeth II -+
+-----------+------+------------+-----------+----------+
| Date      | Time | Location   | Longitude | Latitude |
+-----------+------+------------+-----------+----------+
| 21/4/1926 | 2:40 | London, GB | -0.12574  | 51.50853 |
+-----------+------+------------+-----------+----------+
+-----------+------+-------+------+---------------+
| Planet    | Sign | Pos.  | Ret. | House         |
+-----------+------+-------+------+---------------+
| Sun       | Tau  | 0.21  | -    | Second_House  |
| Moon      | Leo  | 12.12 | -    | Seventh_House |
| Mercury   | Ari  | 4.66  | -    | Second_House  |
| Venus     | Pis  | 13.96 | -    | First_House   |
| Mars      | Aqu  | 20.87 | -    | First_House   |
| Jupiter   | Aqu  | 22.51 | -    | First_House   |
| Saturn    | Sco  | 24.45 | R    | Ninth_House   |
| Uranus    | Pis  | 27.36 | -    | Second_House  |
| Neptune   | Leo  | 22.03 | R    | Seventh_House |
| Pluto     | Can  | 12.71 | -    | Sixth_House   |
| Mean_Node | Can  | 20.47 | R    | Sixth_House   |
| True_Node | Can  | 20.11 | R    | Sixth_House   |
| Chiron    | Ari  | 28.02 | -    | Second_House  |
+-----------+------+-------+------+---------------+
+----------------+------+----------+
| House          | Sign | Position |
+----------------+------+----------+
| First_House    | Cap  | 21.42    |
| Second_House   | Pis  | 18.49    |
| Third_House    | Tau  | 0.34     |
| Fourth_House   | Tau  | 25.59    |
| Fifth_House    | Gem  | 14.13    |
| Sixth_House    | Can  | 1.12     |
| Seventh_House  | Can  | 21.42    |
| Eighth_House   | Vir  | 18.49    |
| Ninth_House    | Sco  | 0.34     |
| Tenth_House    | Sco  | 25.59    |
| Eleventh_House | Sag  | 14.13    |
| Twelfth_House  | Cap  | 1.12     |
+----------------+------+----------+